name: Update IPTV Sources

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行
  workflow_dispatch:       # 允许手动触发

jobs:
  update-sources:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: pip install requests
      
    - name: Update live sources
      run: python scripts/update_sources.py
      
    - name: Update VOD sources
      run: python scripts/update_vod_sources.py
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add outputs/ logs/ README.md
        git commit -m "Auto-update IPTV sources - $(date)"
        git push        python scripts/update_sources.py
        
    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add outputs/ logs/
        git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
